### ISSUE TITLE
Stepfunction Event logger TODO

### ISSUE THREAD

**Issue by leothomas** [developmentseed/cdk-seed#13]
Next steps for the stepfunction event logger, in decreasing order of priority (and complexity):

- [ ] Add CDK code [here](https://github.com/developmentseed/cdk-seed/blob/cc1956aa9d82ea7dd8f4e7eeac6ea9a4edc8faf1/packages/stepfunction-event-logger/lib/index.ts#L214-L220), to spin up necessary Postgres infrastructure if the user selects the `POSTGRES` datastore options 
- [ ] Add python code [here](https://github.com/developmentseed/cdk-seed/blob/cc1956aa9d82ea7dd8f4e7eeac6ea9a4edc8faf1/packages/stepfunction-event-logger/lib/lambda/event_logger.py#L89-L9) to format and send stepfunction history items to Postgres datastore 
- [ ] Add unit tests + integration tests for the lambda function 
- [ ] Implement user-configurable DynamoDB indexes and capacity scaling (to allow user finer grain control over the most cost intensive aspects of the seed)
